const PDFDocument = require('pdfkit');

const generateTenantPDF = (tenant) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      // Nestify Header with Branding
      doc.rect(0, 0, doc.page.width, 80).fill('#2563eb');
      doc.fontSize(28).fillColor('white').text('NESTIFY', 50, 25, { align: 'left' });
      doc.fontSize(12).text('Hostel Management System', 50, 55);
      doc.fillColor('black');
      
      // Document Title
      doc.moveDown(2);
      doc.fontSize(22).fillColor('#1f2937').text('TENANT INFORMATION REPORT', { align: 'center' });
      doc.moveDown();
      
      // Hostel Info Box
      if (tenant.admins?.hostel_name) {
        doc.rect(50, doc.y, doc.page.width - 100, 60).stroke('#e5e7eb');
        doc.fontSize(16).fillColor('#374151').text(tenant.admins.hostel_name, 60, doc.y + 15, { align: 'center' });
        if (tenant.admins.hostel_address) {
          doc.fontSize(11).fillColor('#6b7280').text(tenant.admins.hostel_address, 60, doc.y + 10, { align: 'center' });
        }
        doc.moveDown(2);
      }

      // Personal Information Section
      doc.fontSize(16).fillColor('#1f2937').text('Personal Information', { underline: true });
      doc.moveDown(0.5);
      
      const personalInfo = [
        ['Registration ID', tenant.registration_id],
        ['Full Name', tenant.name],
        ['Email Address', tenant.email],
        ['Phone Number', tenant.phone],
        ['Alternate Phone', tenant.alt_phone || 'N/A'],
        ['Address', tenant.address || 'N/A'],
        ['Admission Date', new Date(tenant.admission_date).toLocaleDateString('en-IN')],
        ['Status', tenant.is_active ? 'Active' : 'Inactive']
      ];

      personalInfo.forEach(([label, value]) => {
        doc.fontSize(11).fillColor('#374151').text(`${label}:`, 50, doc.y, { continued: true, width: 150 });
        doc.fillColor('#1f2937').text(value, 200);
        doc.moveDown(0.3);
      });
      
      doc.moveDown();

      // Room Information Section
      if (tenant.rooms) {
        doc.fontSize(16).fillColor('#1f2937').text('Room Information', { underline: true });
        doc.moveDown(0.5);
        
        const roomInfo = [
          ['Room Number', tenant.rooms.room_number],
          ['Room Type', tenant.rooms.room_type],
          ['Location', tenant.rooms.location || 'N/A'],
          ['Monthly Rent', `₹${tenant.rooms.rent_amount}`]
        ];

        roomInfo.forEach(([label, value]) => {
          doc.fontSize(11).fillColor('#374151').text(`${label}:`, 50, doc.y, { continued: true, width: 150 });
          doc.fillColor('#1f2937').text(value, 200);
          doc.moveDown(0.3);
        });
      }

      // Footer
      doc.moveDown(2);
      doc.rect(50, doc.page.height - 100, doc.page.width - 100, 1).fill('#e5e7eb');
      doc.fontSize(10).fillColor('#6b7280')
         .text(`Generated by Nestify Hostel Management System`, 50, doc.page.height - 80)
         .text(`Report Date: ${new Date().toLocaleString('en-IN')}`, 50, doc.page.height - 65)
         .text('This is a computer-generated document.', 50, doc.page.height - 50);

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

const generateInvoicePDF = (bill) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      // Nestify Header with Branding
      doc.rect(0, 0, doc.page.width, 80).fill('#2563eb');
      doc.fontSize(28).fillColor('white').text('NESTIFY', 50, 25, { align: 'left' });
      doc.fontSize(12).text('Hostel Management System', 50, 55);
      doc.fillColor('black');
      
      // Invoice Title
      doc.moveDown(2);
      doc.fontSize(22).fillColor('#1f2937').text('PAYMENT INVOICE', { align: 'center' });
      doc.moveDown();

      // Bill Information
      doc.fontSize(16).fillColor('#1f2937').text('Bill Information', { underline: true });
      doc.moveDown(0.5);
      
      const billInfo = [
        ['Bill Number', bill.bill_number],
        ['Billing Period', `${bill.billing_month}/${bill.billing_year}`],
        ['Tenant Name', bill.tenants?.name || 'N/A'],
        ['Room Number', bill.rooms?.room_number || 'N/A']
      ];

      billInfo.forEach(([label, value]) => {
        doc.fontSize(11).fillColor('#374151').text(`${label}:`, 50, doc.y, { continued: true, width: 150 });
        doc.fillColor('#1f2937').text(value, 200);
        doc.moveDown(0.3);
      });
      
      doc.moveDown();

      // Charges Table
      doc.fontSize(16).fillColor('#1f2937').text('Charges Breakdown', { underline: true });
      doc.moveDown(0.5);
      
      const charges = [
        ['Room Rent', bill.room_rent],
        ['Electricity Charges', bill.electricity_charges],
        ['Water Charges', bill.water_charges],
        ['Maintenance Charges', bill.maintenance_charges],
        ['Internet Charges', bill.internet_charges],
        ['Other Charges', bill.other_charges]
      ].filter(([, amount]) => parseFloat(amount) > 0);

      charges.forEach(([label, amount]) => {
        doc.fontSize(11).fillColor('#374151').text(label, 50, doc.y, { continued: true, width: 300 });
        doc.fillColor('#1f2937').text(`₹${parseFloat(amount).toFixed(2)}`, 400, doc.y, { align: 'right' });
        doc.moveDown(0.3);
      });
      
      // Total
      doc.moveDown(0.5);
      doc.rect(50, doc.y, doc.page.width - 100, 1).fill('#e5e7eb');
      doc.moveDown(0.5);
      doc.fontSize(14).fillColor('#1f2937').text('Total Amount:', 50, doc.y, { continued: true, width: 300 });
      doc.fontSize(16).fillColor('#059669').text(`₹${parseFloat(bill.total_amount).toFixed(2)}`, 400, doc.y, { align: 'right' });

      // Payment Information
      if (bill.transactions) {
        doc.moveDown(2);
        doc.fontSize(16).fillColor('#1f2937').text('Payment Information', { underline: true });
        doc.moveDown(0.5);
        
        const paymentInfo = [
          ['Payment Method', bill.transactions.payment_method],
          ['Payment Date', new Date(bill.transactions.transaction_date).toLocaleString('en-IN')],
          ['Transaction ID', bill.transactions.razorpay_payment_id || 'N/A']
        ];

        paymentInfo.forEach(([label, value]) => {
          doc.fontSize(11).fillColor('#374151').text(`${label}:`, 50, doc.y, { continued: true, width: 150 });
          doc.fillColor('#1f2937').text(value, 200);
          doc.moveDown(0.3);
        });
      }

      // Footer
      doc.moveDown(2);
      doc.rect(50, doc.page.height - 100, doc.page.width - 100, 1).fill('#e5e7eb');
      doc.fontSize(10).fillColor('#6b7280')
         .text(`Generated by Nestify Hostel Management System`, 50, doc.page.height - 80)
         .text(`Invoice Date: ${new Date().toLocaleString('en-IN')}`, 50, doc.page.height - 65)
         .text('Thank you for your payment!', 50, doc.page.height - 50);

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = {
  generateTenantPDF,
  generateInvoicePDF
};