const PDFDocument = require('pdfkit');

const generatePaymentReportPDF = async (transactions, dateRange) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Header
      doc.fontSize(24).font('Helvetica-Bold').fillColor('#2563eb').text('NESTIFY', 50, 50);
      doc.fontSize(14).fillColor('#6b7280').text('Hostel Management System', 50, 85);
      doc.fontSize(18).fillColor('#1f2937').text('PAYMENT REPORT', 400, 50);
      
      // Date range
      doc.fontSize(10).text(`Period: ${dateRange.startDate} to ${dateRange.endDate}`, 400, 75);
      doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 400, 90);

      let yPosition = 150;
      yPosition = generatePaymentReport(doc, transactions, yPosition);

      // Footer
      doc.fontSize(8).fillColor('#9ca3af').text('Generated by Nestify Hostel Management System © 2025', 50, 750);

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};



const generatePaymentReport = (doc, transactions, yPosition) => {
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#1f2937').text('Payment Summary', 50, yPosition);
  yPosition += 30;

  // Summary
  const totalAmount = transactions.reduce((sum, txn) => sum + parseFloat(txn.amount), 0);
  doc.fontSize(12).font('Helvetica').text(`Total Transactions: ${transactions.length}`, 50, yPosition);
  doc.text(`Total Amount: Rs.${totalAmount.toFixed(2)}`, 300, yPosition);
  yPosition += 40;

  // Table header
  doc.fontSize(10).font('Helvetica-Bold');
  doc.text('Date', 50, yPosition);
  doc.text('Tenant', 150, yPosition);
  doc.text('Amount', 300, yPosition);
  doc.text('Method', 400, yPosition);
  yPosition += 20;

  doc.moveTo(50, yPosition).lineTo(550, yPosition).stroke();
  yPosition += 10;

  // Table rows
  doc.font('Helvetica');
  transactions.forEach((txn) => {
    if (yPosition > 700) {
      doc.addPage();
      yPosition = 50;
    }
    
    doc.text(new Date(txn.transaction_date).toLocaleDateString('en-IN'), 50, yPosition);
    doc.text(txn.tenants?.name || 'N/A', 150, yPosition);
    doc.text(`Rs.${parseFloat(txn.amount).toFixed(2)}`, 300, yPosition);
    doc.text(txn.payment_method, 400, yPosition);
    yPosition += 20;
  });

  return yPosition;
};

module.exports = { generatePaymentReportPDF };